fixing docs
clastix/coaks-baseline-architecture pull request #18
Opened 2023-08-31 08:02 UTC by ppodevlabs

Fix #17 

Fixed some broken links and extended a bit the capsule proxy configuration to use ssl, ingress etc.

2023-09-01 10:01 UTC, maxgio92 commented
Hey @ppodevlabs, thank you.

LGTM

/cc @prometherion @bsctl

2023-09-05 09:19 UTC, prometherion requested changes

2023-09-05 09:19 UTC, prometherion commented on README.md
> +3. [Setup a Multitenancy Environment](guides/04-multitenant-environment.md)
```suggestion
1. [AKS Creation with AAD integration](guides/01-create-aks-with-add.md)
2. [Capsule Installation](guides/02-capsule-installation.md)
3. [Capsule Proxy Installation](guides/03-capsule-proxy-installation.md)
4. [Setup a Multitenancy Environment](guides/04-multitenant-environment.md)
```

2023-09-13 07:57 UTC, prometherion commented on README.md
> +3. [Setup a Multitenancy Environment](guides/04-multitenant-environment.md)
@ppodevlabs may I ask you to address these changes?

The PR looks very good, just a minor thing to get it merged!

2023-10-09 10:21 UTC, ppodevlabs commented
Sorry for the delay i missed the notification

2023-10-12 09:56 UTC, merged